// <auto-generated />
namespace AppleStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_IsPurchasedBoolToPurchasedApples_Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsPurchasedBoolToPurchasedApples_Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202202222309328_Add_IsPurchasedBoolToPurchasedApples_Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
