// <auto-generated />
namespace AppleStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_IsCompletedColumn_InPurchasedApplesEntity_Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsCompletedColumn_InPurchasedApplesEntity_Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202202280056226_Add_IsCompletedColumn_InPurchasedApplesEntity_Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
